[package]
name = "newsapi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ureq = "2.7.0"
serde_json = "1.0.97"
serde = {version = "1.0.164", features =["derive"]}
thiserror = "1.0.40"
